import type { Metadata } from "next";

import "../styles/globals.css";

import { Inter as FontSans } from "next/font/google";
import localFont from "next/font/local";
import { getServerSession } from "next-auth";
import { Toaster } from "sonner";

import { authOptions } from "@/lib/authOptions";
import { cn } from "@/lib/utils";
import { TailwindIndicator } from "@/components/ui/tailwind-indicator";
import { Providers } from "@/components/providers";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontHeading = localFont({
  src: "./fonts/CalSans-SemiBold.woff2",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              try {
                if (localStorage.theme === 'dark' || ((!('theme' in localStorage) || localStorage.theme === 'system') && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
                  document.querySelector('meta[name="theme-color"]').setAttribute('content', '#09090b')
                }
              } catch (_) {}
            `,
          }}
        />
      </head>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
          fontHeading.variable
        )}
      >
        <div className="flex min-h-screen flex-col">
          <main className="flex-1">
            <Providers session={session}>
              <div vaul-drawer-wrapper="" className="bg-background">
                {children}
                <Toaster position="top-right" richColors />
                <TailwindIndicator />
              </div>
            </Providers>
          </main>
        </div>
      </body>
    </html>
  );
}
